config/routes.rb
Rails.application.routes.draw do
  resources :tweets
  root 'tweets#index'
end

app/models/tweet.rb
class Tweet < ActiveRecord::Base
  validates :message, presence: true, length: {maximum: 140}
  
  #def hello2
    #logger.debug "Modelですよ"
  #end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  #def hello
    #logger.debug "application_controller"
  #end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  def index
    @tweets = Tweet.all
    #hello
    #logger.debug "test"
    #tweet.new.hello2
  end
  
  def new
    @tweet = Tweet.new
  end
  
  def create
  @tweet = Tweet.new(message: params[:tweet][:message], tdate: params[:tweet][:tdate])
    if @tweet.save
      redirect_to root_path
    else
      render 'new'
    end
  end
  
  def destroy
  @tweet = Tweet.find(params[:id])
  @tweet.destroy
  redirect_to root_path
  end
  
  def show
  @tweet = Tweet.find(params[:id])
  end
  
  def edit
  @tweet = Tweet.find(params[:id])
  end

  def update
    @tweet = Tweet.find(params[:id])
    @tweet.update(message: params[:tweet][:message], tdate: params[:tweet][:tdate])
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Twitter</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div id="container">
    <div id="header">
      <%= render "header" %>
    </div>
    <div class="side">
    <div id="sidebar">
      <%= render "sidebar" %>
    </div>
    <div id="content" %>
      <%= yield %>
    </div>
    <div id="footer" %>
      <%= render "footer" %>
    </div>
  </div>
  </div>
</body>
</html>

app/views/tweets/_footer.html.erb
<fotter>
  <p>Copyright &copy; 2018 Twitter&ensp;
  <a href="#">Twitterについて</a><br/>
  <a href="#">ヘルプセンター</a>
  <a href="#">規約</a>
  <a href="#">プライバシーポリシー</a><br/>
  <a href="#">クッキー</a>
  <a href="#">広告について</a>
  </p>
</fotter>

app/views/tweets/_form.html.erb
<%= f.text_area :message, size: "50x4" %>
<% @tweet.tdate = Time.current %>
<%= f.hidden_field :tdate %><br/>
<%= f.submit 'ツイート' %>

app/views/tweets/_header.html.erb
<header>
    <img src="/assets/t1.jpg", id=headerImg1>
<div class="side">
    <img src="/assets/t2.jpg", id="headerImg2">
</div>
</header>

app/views/tweets/_sidebar.html.erb
<h1>近畿大学</h1>
<h2>
  <a class="nameLink" href="https://twitter.com/kinkidaigakuPR">@kinkidaigakuPR</a>
</h2>
<p>近畿大学総務部広報室のTwitter公式アカウントです。
近畿大学ホームページの更新情報を中心に、大学に関する情報を発信していきます。
個別DMでのお問い合わせには返信を行っておりませんので、ご了承ください。</p>

<p>大阪府東大阪市</p>
<a href="instagram.com/kinkidaigakupr/">instagram.com/kinkidaigakupr/</a>
<p>2010年12月に登録</p>
<p>
    <%= link_to "ツイート", new_tweet_path, class: "btn" %>
    <%= link_to "ダイレクト", new_tweet_path, class: "btn" %>
</p>
<br/>

app/views/tweets/edit.html.erb
<%= form_for @tweet do |f| %>
   <%= render "form", f: f %>
<% end %>
  

app/views/tweets/index.html.erb
<html>
  <head>
    <title>Twitter</title>
  </head>
  <body id="page">
<% @tweets.each do |t|%>
<br/>
  <%= t.message %>&ensp;
  <%= (Time.current - t.tdate).to_i / 60 %>分前&ensp;
  <%= link_to '表示', tweet_path(t) %>
  <%= link_to '編集', edit_tweet_path(t) %>
  <%= link_to '削除', tweet_path(t), method: :delete %>
  <br/><br/><hr><br/>
<% end %>
 </body>
</html>

app/views/tweets/new.html.erb
<% if @tweet.errors.present? %>
<h3>エラーがあります。</h3>
<ul>
  <% @tweet.errors.full_messages.each do |msg| %>
  <li><%= msg %></li>
  <% end %>
</ul>
<% end %>
<br/>
<%= form_for @tweet do |f| %>
 <%= render "form", f: f %>
<% end %>

app/views/tweets/show.html.erb
<p>
  <%= @tweet.message %>
&ensp;
  <%= (Time.current - @tweet.tdate).to_i / 60 %>分前
</p>

<%= link_to 'Back',root_path %>